import type {NextPage} from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Portfolio - Dominik Obłoza</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={'grid justify-center'}>
                <div className="max-w-5xl w-full py-10">

                    <div className="flex justify-end gap-9 text-justWhite-dark">
                        <div className="text-extra-color">
                            home
                        </div>
                        <div className={'transition-all hover:text-justWhite-light cursor-pointer'}>
                            projects
                        </div>
                        <div className={'transition-all hover:text-justWhite-light cursor-pointer'}>
                            contact
                        </div>
                    </div>


                    <div className="text-5xl mt-20">
                        Dominik Obłoza
                    </div>

                    <div className="mt-10 text-justWhite-dark text-xl">
                        lorem ipsum <span className={'text-extra-color'}>dolor sit</span> amet, consectetur adipiscing
                        elit. Nam mi lacus, pulvinar in vulputate
                        sed, placerat nec enim. Morbi venenatis id ipsum non <span className={'text-justWhite-light'}>
                        lacinia</span>.
                        <br /><br />
                        Etiam vel nulla at nisi <span className={'text-justWhite-light'}>aliquam</span> gravida.
                        Phasellus lacus arcu, pretium tristique libero vel,
                        suscipit vulputate felis. In tempus dictum <span className={'text-extra-color'}>ligula</span>,
                        eu vestibulum turpis placerat vel.
                    </div>
                </div>
            </div>
        </div>
    )
}

export default Home
